apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: aliyun-provisioner
  name: aliyun-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aliyun-provisioner
  template:
    metadata:
      labels:
        app: aliyun-provisioner
    spec:
      serviceAccountName: persistent-volume-provisioner
      containers:
      - env:
        - name: ALIYUN_ACCESSKEY_ID
          valueFrom:
            secretKeyRef:
              name: aliyun-access-key
              key: id
        - name: ALIYUN_ACCESSKEY_SECRET
          valueFrom:
            secretKeyRef:
              name: aliyun-access-key
              key: secret
        image: xuyuanp/aliyun-provisioner:v0.1.2
        args:
        - -v=2
        name: aliyun-provisioner
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
